### ISSUE TITLE
Improper rending of non-ASCII characters in descriptions

### ISSUE THREAD

**Issue by GilOliveira** [podverse/podverse-rn#1513]
**Describe the bug**
When a podcast uses non-ASCII characters in its description (such as accented letters), the app doesn’t properly render them. This issue only happens in the short trimmed blurb in on the top of the episode list; when you tap the text to read it all it renders fine.

**To Reproduce**
1. Add a podcast with non-ASCII characters in its description to your library
2. Tap the cover to open it
3. In the “Podcast” page with the episodes list, the description underneath the podcast title doesn’t render Unicode text correctly (e.g “&iaccute” appears instead of “í”)
4. Tap the text to reveal to read it in full
5. The “More Info” page appears, the full text now renders fine.

**Expected behavior**
The app should parse the non-Unicode characters and display them properly, like it does in the rest of the app.

**Screenshots**
![5D2F9014-83E0-41A0-856B-F7C11AB11923](https://user-images.githubusercontent.com/1360438/208090713-6d69a9b5-6837-4684-b75d-53c727067e71.jpeg)
![6C921FB1-3A70-485E-A012-886A11127FBF](https://user-images.githubusercontent.com/1360438/208090727-2cb0b8ac-7b85-432a-b6dd-aef8aec789f5.jpeg)

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: iOS 16.1.1
 - App Version: 4.9.0 (1936) (TestFlight)

**Additional context**
The use of non-ASCII Unicode characters is very common on many languages other then English.

**Comment by mitchdowney** [comment]
@GilOliveira great bug report! I think we have addressed this issue in other text components, so hopefully it is easy to fix...

**Comment by mitchdowney** [comment]
This should be in v4.10.0

![image](https://user-images.githubusercontent.com/2262919/208357881-998e2ddb-a34b-49d7-b372-c9f651e6e3ec.png)

**Comment by erifneerg** [comment]
![image](https://github.com/podverse/podverse-rn/assets/106611/855736cb-6b2b-48d3-98e3-a96ccffd6680)
I'm still seeing the issue with other podcast. I wasn't sure if i should open a new issue or just comment here but figured I'd share it here at least.
